name: Sample workflow for App Center action
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: maierj/fastlane-action@v2.0.1
        with:
            lane: 'deployAppCenter'
            skip-tracking: true
